config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'issues#index', as: :authenticated_root, constraints: RoleConstraint.new(:reporter)
  root 'admin/users#index', as: :admin_root, constraints: RoleConstraint.new(:admin)
  root 'staff/issues#index', as: :staff_root, constraints: RoleConstraint.new(:staff)
  root 'public#index'

  namespace :admin do
    resources :users
  end

  namespace :staff do
    resources :issues, only: %i[index edit update destroy]
  end

  resources :issues do
    member do
      put 'reopen', to: 'issues#reopen'
    end
  end
  resources :public, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :title, presence: true

  enum status: {
    open: 0,
    waiting: 1,
    closed: 2,
    waiting_confirmation: 3,
    finished: 4
  }

  enum priority: {
    low: 0,
    medium: 1,
    high: 2,
    urgent: 3
  }

  scope :active, -> { where(status: %i[open waiting waiting_confirmation]) }
  scope :inactive, -> { where(status: %i[closed finished]) }

  belongs_to :reporter, class_name: 'User', foreign_key: :reported_by
  belongs_to :location

  def self.options_for_priority_select
    priorities.keys.map do |priority|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.priorities.#{priority}"), priority]
    end
  end

  def self.options_for_status_select
    statuses.keys.map do |status|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.statuses.#{status}"), status]
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, :floor, presence: true

  enum floor: {
    first: 'first',
    second: 'second',
    third: 'third',
    fourth: 'fourth',
    outside: 'outside'
  }, _suffix: :floor

  has_many :issues

  def self.options_for_floor_select
    floors.keys.map do |floor|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.floor.#{floor}"), floor]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable, :validatable

  enum role: {
    reporter: 0,
    staff: 1,
    admin: 2
  }

  has_many :issues, foreign_key: :reported_by

  before_save :set_role

  private

  def set_role
    self.role ||= :reporter
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_issue, only: %i[show edit update destroy reopen]

  def index
    @issues = current_user.issues
  end

  def show
    authorize! :read, @issue
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params.merge(reporter: current_user))
    if @issue.save
      redirect_to @issue
    else
      flash.now[:alert] = @issue.errors.full_messages
      render :new
    end
  end

  def edit
    authorize! :update, @issue
  end

  def destroy
    authorize! :destroy, @issue
    @issue.update(status: Issue.statuses[:closed])
    render :show
  end

  def update
    authorize! :update, @issue

    if @issue.update(issue_params)
      redirect_to @issue
    else
      flash.now[:alert] = @issue.errors.full_messages
      render :edit
    end
  end

  def reopen
    authorize! :update, @issue

    if @issue.update(status: :open)
      redirect_to root_path, notice: 'Incidente reaberto.'
    else
      redirect_to root_path, alert: 'Não foi possível reabrir o incidente.'
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:title, :description, :location_id)
  end

  def find_issue
    @issue = Issue.find(params[:id])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  layout false

  def index
  end
end

app/controllers/staff/issues_controller.rb
class Staff::IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_issue, only: %i[edit update destroy]

  def index
    authorize! :read, Issue
    @issues = Issue.all
  end

  def edit
    authorize! :update, @issue
  end

  def update
    authorize! :update, @issue
    if @issue.update(issue_params)
      redirect_to root_path, notice: 'Incidente atualizado.'
    else
      redirect_to staff_issue_path(@issue), alert: 'Não foi possível atualizar incidente.'
    end
  end

  def destroy
    authorize! :update, @issue
    if @issue.update(status: :closed)
      redirect_to root_path, notice: 'Incidente fechado.'
    else
      redirect_to staff_issue_path(@issue), alert: 'Não foi possível fechar incidente.'
    end
  end

  private

  def find_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:status, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="admin-incidentes">
  <h1>Editar funcionário <%= @user.email %></h1>
</div>
<div class="forms">
  <%= render partial: 'form', locals: { user: @user, path: admin_user_path(@user) } %>
</div>

app/views/admin/users/index.html.erb
<div class="super-admin-user-list">
  <h1>Funcionários</h1>
  <% if @users.any? %>
    <table>
      <thead>
        <th>Email</th>
        <th>Criado em</th>
        <th>Ações</th>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td>
            <p><%= user.email %></p>
          </td>
          <td>
            <%= I18n.l(user.created_at, format: :short) %>
          </td>
          <td class="inline">
            <%= link_to 'Editar', edit_admin_user_path(user) %>
            <%= button_to 'Excluir', admin_user_path(user), method: :delete %>
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>Nenhum funcionário cadastrado.</p>
  <% end %>

  <%= link_to "Cadastrar novo usuário", new_admin_user_path %>
</div>

app/views/admin/users/show.html.erb
<div class="super-admin-user-list">
<h1> Usuário criado com sucesso </h1>
<table>
  <thead>
    <th>Email</th>
    <th>Criado em</th>
    <th>Ações</th>
  </thead>
  <tr>
    <td>
      <%= @user.email %>
    </td>
    <td>
      <%= I18n.l(@user.created_at, format: :short) %>
    </td>
    <td>
      <%= link_to 'Editar', edit_admin_user_path(@user) %>
      <%= button_to 'Excluir', admin_user_path(@user), method: :delete %>
    </td>
  </tr>
</table>
</div>

app/views/issues/_form.html.erb
<%= form_for issue do |f| %>
  <div class="container">
    <div class="text-areas">
        <%= f.label :Título %>
        <%= f.text_field :title %>
    </div>
      <br>
    <div class="text-areas">
        <%= f.label :Descrição %>
        <%= f.text_area :description %>
    </div><br />
    <div class="text-areas">
        <%= f.label :Local %>
        <%= f.select :location_id, options_for_select(
          Location.all.map { |l| [l.name, l.id] }
        ) %>
    </div><br />
      <%=f.submit :OK, :id=>"button" %>  
      <% end %>
    </div>

app/views/issues/edit.html.erb
<div  class="admin-incidentes">
    <h1>Editar incidente</h1>
</div>

<%= render partial: 'form', locals: { issue: @issue } %>

app/views/issues/index.html.erb
<% content_for :menu_items do %>
  <%= link_to "Registrar incidente", new_issue_path %>
<% end %>
<div class="admin-incidentes">
  <div class="container">
  <% if @issues.active.any? %>
    <h1>Incidentes ativos</h1>
    <% @issues.active.each do |issue| %>
      <div class="incidente">
          <div class="incidente-infos">
            <span class="data">
              Criado em:
              <%= I18n.l(issue.created_at, format: :short) %>
              Última atualização em:
              <%= I18n.l(issue.updated_at, format: :short) %>
            </span>
            <div class="incidente-titulo">
              <h3><a href="/issues/<%= issue.id %>"> <%= issue.title %></a></h3>
              <span class="status <%= issue.status %>"><%= issue.status %></span>
            </div>
            <p class="localizacao">Localização: <%= issue.location.name %></p>
            <p>Descrição: <%= issue.description %></p>
          </div>
          <div class="incidente-acoes">
            <%= link_to "Editar", edit_issue_path(issue) %>
            <%= button_to "Abandonar", issue, method: :delete %>
          </div>
        </div>
      <% end %>
    <% end %>

    <% if @issues.inactive.any? %>
      <h1>Incidentes inativos</h1>
      <% @issues.inactive.each do |issue| %>
        <div class="incidente">
          <div class="incidente-infos">
            <span class="data">
              Criado em:
              <%= I18n.l(issue.created_at, format: :short) %>
              Última atualização em:
              <%= I18n.l(issue.updated_at, format: :short) %>
            </span>
            <div class="incidente-titulo">
              <h3><%= issue.title %></h3>
              <span class="status <%= issue.status %>"><%= issue.status %></span>
              <span class="priority <%= issue.priority %>"><%= issue.priority %></span>
            </div>
            <p class="localizacao">Localização: <%= issue.location.name %></p>
            <p>Descrição: <%= issue.description %></p>
          </div>
          <div class="incidente-acoes">
            <%= button_to "Reabrir", reopen_issue_path(issue), method: :put %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/issues/new.html.erb
<% content_for :menu_items do %>
  <%= link_to "Registrar incidente", new_issue_path %>
<% end %>
<div class="container">
  <div class="admin-incidentes">
    <h1>Novo incidente</h1>
  </div>
  <div class="forms">
    <%= render partial: 'form', locals: { issue: @issue } %>
  </div>
</div>

app/views/issues/show.html.erb
<% content_for :menu_items do %>
  <%= link_to "Registrar incidente", new_issue_path %>
<% end %>
<div class="issue">
  <div class="title">
    <p>Incidente: <%= @issue.title %></p>
  </div>
  <div class="details">
    <p><b>Última atualização em:</b>
    <%= I18n.l(@issue.updated_at, format: :short) %> (criado em <%= I18n.l(@issue.created_at, format: :short) %>)</p>
    <p class="localizacao">Localização: <%= @issue.location.name %></p>
    <br>
    <p><span class="status <%= @issue.status %>"><%= @issue.status %></span>
  </div>


  <div class="description">
    <h1>Descrição:</h1>
    <%= @issue.description %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfraIssues</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header class="header">
      <%= link_to "Home", root_path %>
      <%= yield :menu_items %>
      <% if user_signed_in? %>
        <%= button_to "Sair", destroy_user_session_path, method: :delete, class: 'link', :id=>"exit_button" %>
      <% end %>
    </header>
    <% %i[notice alert].each do |type| %>
      <% if flash[type] %>
        <div class="flash <%= type %>">
          <%= flash[type] %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/staff/issues/edit.html.erb
<div  class="admin-incidentes">
  <h1>Editar incidente</h1>
</div>

<div class="issue">
  <div class="title">
    <p>Incidente: <%= @issue.title %></p>
  </div>
  <div class="details">
    <p><b>Última atualização em:</b>
    <%= I18n.l(@issue.updated_at, format: :short) %> (criado em <%= I18n.l(@issue.created_at, format: :short) %>)</p>
    <p class="localizacao">Localização: <%= @issue.location.name %></p>
    <br>
    <p><span class="status <%= @issue.status %>"><%= @issue.status %></span>
  </div>


  <div class="description">
    <h1>Descrição:</h1>
    <%= @issue.description %>
  </div>
</div>

<%= form_for @issue, url: staff_issue_path(@issue) do |f| %>
  <div class="container">
    <div class="text-areas">
      <%= f.label 'Status' %>
      <%= f.select :status, options_for_select(Issue.options_for_status_select, @issue.status) %>
    </div>
    <br>
    <div class="text-areas">
      <%= f.label 'Prioridade' %>
      <%= f.select :priority, options_for_select(Issue.options_for_priority_select, @issue.priority) %>
    </div><br />
    <%=f.submit 'Atualizar', :id=>"button" %>
  </div>
<% end %>

app/views/staff/issues/index.html.erb
<div class="admin-incidentes">
  <div class="container">
  <% if @issues.any? %>
    <h1>Incidentes</h1>
    <% @issues.each do |issue| %>
      <div class="incidente">
          <div class="incidente-infos">
            <span class="data">
              Criado em:
              <%= I18n.l(issue.created_at, format: :short) %>
              Última atualização em:
              <%= I18n.l(issue.updated_at, format: :short) %>
            </span>
            <div class="incidente-titulo">
              <h3><%= issue.title %></h3>
              <span class="status <%= issue.status %>"><%= Issue.human_enum_name(:status, issue.status) %></span>
              <span class="priority <%= issue.priority %>"><%= Issue.human_enum_name(:priority, issue.priority) %></span>
            </div>
            <div class="">
              <p class="localizacao"><strong>Reportado por:</strong> <%= issue.reporter.email %></p>
            </div>
            <p class="localizacao">Localização: <%= issue.location.name %></p>
            <p>Descrição: <%= issue.description %></p>
          </div>
          <div class="incidente-acoes">
            <%= link_to "Editar", edit_staff_issue_path(issue) %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Nenhum incidente reportado.</p>
    <% end %>
  </div>
</div>